# A. Read the dataset file “Credit.csv” (from github using the following command), and assign it to a Pandas DataFrame: df  = pd.read_csv("https://github.com/mpourhoma/CS4661/raw/master/Credit.csv")

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn import preprocessing
from sklearn.linear_model import LinearRegression

import numpy as np
import pandas as pd

In [2]:
#reading csv file and storing it directly in a dataframe
df = pd.read_csv("https://github.com/mpourhoma/CS4661/raw/master/Credit.csv")

# B. Check out the dataset. The “Credit” dataset includes the “balance” column (average credit card debt for a number of individuals) as target, as well as several features: age, cards (number of credit cards), education (years of education), income (in thousands of dollars), limit (credit limit), marital status, and rating (credit rating).

In [5]:
#check dataset every 15 lines
df[0::15]

      Income  Limit  Rating  Cards  Age  Education  Married  Balance
0     14.891   3606     283      2   34         11        1      333
15    20.089   2525     200      3   57         15        1        0
30    34.142   5666     413      4   47          5        1      863
45    77.380   7569     564      3   50         12        1      997
60    35.510   5198     364      2   35         20        0      631
75    33.017   3180     224      2   28         16        1       29
90    20.191   5767     431      4   42         16        1     1023
105   12.031   3182     259      2   58         18        1      210
120   27.241   1402     128      2   67         15        1        0
135   44.473   3500     257      3   81         16        0        8
150   63.931   5728     435      3   28         14        1      581
165   25.383   4527     367      4   46         11        1      570
180   10.635   3584     294      5   69         16        1      423
195   23.883   5384     398      2   73         16        1      802
210   24.543   3206     243      2   62         12        1       95
225   15.079   5673     411      4   28         15        1     1075
240   29.705   3351     262      5   71         14        1      148
255   58.063   4221     304      3   50          8        0      118
270   15.866   3085     217      1   39         13        0      136
285   18.967   1626     156      2   41         11        1        0
300   21.786   4632     355      1   50         17        1      580
315   14.479   3907     296      3   43         16        1      463
330   20.405   4543     329      2   72         17        0     1054
345   30.012   1511     137      2   33         17        1        0
360   53.566   5891     434      4   82         10        0      712
375   20.974   5673     413      5   44         16        1     1000
390  135.118  10578     747      3   81         15        1     1393

# C. Generate the feature matrix and target vector (target is “balance” in this dataset). Then, normalize (scale) the features (note: don’t normalize the target vector!). To normalize the data, you can simply use scale(X)  from sklearn.

In [6]:
# create list of feature names from dataset:

feature_cols = ['Age', 'Cards', 'Education', 'Income', 'Limit', 'Married', 'Rating']

# use list to select the features DataFrame

X = df[feature_cols]

# print the first 5 rows
X.head()

   Age  Cards  Education   Income  Limit  Married  Rating
0   34      2         11   14.891   3606        1     283
1   82      3         15  106.025   6645        1     483
2   71      4         11  104.593   7075        0     514
3   36      3         11  148.924   9504        0     681
4   68      2         16   55.882   4897        1     357

In [8]:
## select the last column from DataFrame

y = df['Balance']

#print first 5 rows

y.head()

0    333
1    903
2    580
3    964
4    331
Name: Balance, dtype: int64

In [9]:
#normalizing the features
X = preprocessing.scale(X)

#printing the dataset
X

array([[-1.2576741 , -0.6991298 , -0.78492991, ..., -0.48999879,
         0.79539491, -0.46553881],
       [ 1.5284506 ,  0.03103187,  0.49658831, ...,  0.82826106,
         0.79539491,  0.82870309],
       [ 0.88996369,  0.76119355, -0.78492991, ...,  1.01478681,
        -1.25723711,  1.02931059],
       ...,
       [ 0.65778663,  1.49135522, -0.46455035, ..., -0.24491264,
         0.79539491, -0.21963285],
       [-0.67723146, -1.42929148, -0.1441708 , ..., -0.95891584,
         0.79539491, -1.05441888],
       [ 0.48365384,  1.49135522, -2.06644812, ...,  0.34199278,
        -1.25723711,  0.38866085]])

# D. Split the dataset into testing and training sets with the following parameters: test_size=0.24, random_state=9.

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.24, random_state=9)

print(X_test)
print('\n')
print(y_test)

[[ 5.41698100e-01  7.61193547e-01  1.76208755e-01  8.82214408e-01
   1.88260868e-02  7.95394909e-01  7.80427871e-02]
 [-4.45054399e-01 -6.99129805e-01 -1.44170799e-01  2.52731915e+00
   1.34576156e+00 -1.25723711e+00  1.34639986e+00]
 [ 7.73875158e-01  3.10318712e-02  4.96588309e-01 -2.47807894e-01
  -1.55120015e-01  7.95394909e-01 -1.03151080e-01]
 [-1.08354131e+00 -1.42929148e+00  1.76208755e-01 -4.49312486e-01
  -1.04480444e+00  7.95394909e-01 -1.14501582e+00]
 [ 8.89963688e-01  7.61193547e-01 -7.84929908e-01  1.68675551e+00
   1.01478681e+00 -1.25723711e+00  1.02931059e+00]
 [-1.60593969e+00 -1.42929148e+00 -1.42568902e+00  1.23610553e-01
   7.15044275e-01  7.95394909e-01  6.02210760e-01]
 [ 1.64453913e+00 -1.42929148e+00 -7.84929908e-01  4.93835825e-01
   1.00654497e+00 -1.25723711e+00  8.15760675e-01]
 [ 7.15830894e-01 -6.99129805e-01  1.76208755e-01 -2.53518090e-01
  -7.68919851e-01 -1.25723711e+00 -7.37329616e-01]
 [ 1.52845060e+00  7.61193547e-01 -4.64550354e-01 -5.46329007e-01
  -1.46904207e+00 -1.25723711e+00 -1.37797936e+00]
 [-5.61142928e-01 -6.99129805e-01 -1.10530946e+00  1.20471266e+00
   1.05469464e+00 -1.25723711e+00  1.03578180e+00]
 [ 1.29627354e+00 -6.99129805e-01 -1.44170799e-01 -6.18430890e-01
  -9.91449402e-01 -1.25723711e+00 -1.13207340e+00]
 [ 2.51476777e-01 -6.99129805e-01 -1.74606857e+00 -3.49511889e-01
  -1.27947986e+00  7.95394909e-01 -1.30032485e+00]
 [-1.08354131e+00  1.49135522e+00  1.77810653e+00 -8.99366872e-01
  -6.39653172e-01  7.95394909e-01 -4.91423653e-01]
 [ 1.93432512e-01  3.10318712e-02 -1.74606857e+00  2.58524597e-01
  -7.25541770e-01 -1.25723711e+00 -6.92031149e-01]
 [ 1.06409648e+00 -6.99129805e-01  4.96588309e-01 -8.06810554e-01
  -1.47424744e+00  7.95394909e-01 -1.55270202e+00]
 [-2.70921605e-01  1.49135522e+00  1.45772697e+00 -6.72379462e-01
   2.79528349e-01  7.95394909e-01  4.21016893e-01]
 [-3.87010134e-01  7.61193547e-01 -1.44170799e-01 -6.23175183e-01
   3.06856540e-01  7.95394909e-01  3.36891169e-01]
 [-4.45054399e-01  7.61193547e-01  1.45772697e+00 -1.75109423e-01
   3.59777798e-01  7.95394909e-01  3.56304798e-01]
 [-2.12877341e-01  3.10318712e-02  1.13734742e+00 -4.28602371e-01
  -1.11377559e+00 -1.25723711e+00 -9.63821950e-01]
 [ 7.73439826e-02  3.10318712e-02  4.96588309e-01 -6.20561561e-01
   3.00783609e-01  7.95394909e-01  2.65707864e-01]
 [-7.93319987e-01  7.61193547e-01  8.16967863e-01 -7.11015617e-01
   4.47401520e-01  7.95394909e-01  4.92200198e-01]
 [-5.03098664e-01 -1.42929148e+00  1.45772697e+00 -6.32947857e-01
   8.12905224e-02  7.95394909e-01  3.88272573e-04]
 [ 7.73875158e-01 -6.99129805e-01  1.76208755e-01  1.99717997e+00
   1.96780323e+00 -1.25723711e+00  1.94822235e+00]
 [ 1.18018501e+00  3.10318712e-02  1.45772697e+00 -4.49397713e-01
   4.52867158e-02  7.95394909e-01  8.45139967e-02]
 [-2.12877341e-01 -1.42929148e+00  8.16967863e-01 -3.27409736e-01
   6.74095367e-02 -1.25723711e+00  9.09852062e-02]
 [-8.51364252e-01 -6.99129805e-01  1.76208755e-01  1.68363053e+00
   1.04298256e+00  7.95394909e-01  9.84012124e-01]
 [ 1.47040633e+00  3.10318712e-02 -4.64550354e-01  2.50883587e-02
   1.92772189e-01  7.95394909e-01  1.75110930e-01]
 [-7.93319987e-01  7.61193547e-01 -1.44170799e-01 -6.54509246e-02
  -9.55879377e-01  7.95394909e-01 -9.70293159e-01]
 [-1.43180690e+00 -6.99129805e-01  4.96588309e-01  1.79348889e-01
   1.56334601e-01  7.95394909e-01  1.62168511e-01]
 [-3.87010134e-01 -6.99129805e-01  4.96588309e-01 -1.62750541e-02
  -1.32129632e-01  7.95394909e-01 -2.26104062e-01]
 [-1.78007249e+00  3.10318712e-02  4.96588309e-01 -4.44653421e-01
   2.48729912e-01 -1.25723711e+00  2.72179074e-01]
 [-9.09408516e-01 -6.99129805e-01  1.45772697e+00 -6.04254831e-01
   2.63478459e-01  7.95394909e-01  1.81582140e-01]
 [ 8.89963688e-01  3.10318712e-02 -7.84929908e-01 -9.54991571e-01
  -1.06605970e+00  7.95394909e-01 -1.08677493e+00]
 [-6.19187193e-01  7.61193547e-01 -1.10530946e+00 -8.27151353e-01
   2.83866157e-01  7.95394909e-01  4.08074474e-01]
 [-5.61142928e-01  1.49135522e+00  1.13734742e+00 -8.84508998e-01
  -1.68332978e+00  7.95394909e-01 -1.52034597e+00]
 [ 7.73875158e-01  1.49135522e+00  8.16967863e-01 -9.82491423e-01
  -4.99541972e-01  7.95394909e-01 -3.94355510e-01]
 [ 1.18018501e+00  3.10318712e-02 -1.42568902e+00  7.02385834e-01
   1.22300159e+00  7.95394909e-01  1.24286051e+00]
 [-4.45054399e-01  1.49135522e+00 -1.74606857e+00  5.34318561e-01
   1.92338408e-01  7.95394909e-01  2.78650283e-01]
 [ 7.73439826e-02  3.10318712e-02  4.96588309e-01 -7.13913329e-01
  -9.58915842e-01  7.95394909e-01 -1.00264921e+00]
 [ 5.41698100e-01 -6.99129805e-01 -1.44170799e-01 -7.92691312e-01
  -1.47511500e+00 -1.25723711e+00 -1.40386420e+00]
 [-5.61142928e-01 -6.99129805e-01  8.16967863e-01  2.27217948e-01
   8.99661385e-02  7.95394909e-01  4.56867394e-02]
 [-2.12877341e-01  3.10318712e-02 -1.42568902e+00  4.06563570e-01
   1.20695171e+00 -1.25723711e+00  1.21697567e+00]
 [-1.19962984e+00  7.61193547e-01 -1.74606857e+00 -4.95022466e-01
  -4.02808853e-01  7.95394909e-01 -3.49057043e-01]
 [-2.70921605e-01  2.22151690e+00 -7.84929908e-01 -5.11073516e-01
  -5.42920053e-01 -1.25723711e+00 -4.72010024e-01]
 [-7.35275722e-01  1.49135522e+00  8.16967863e-01 -4.62437415e-01
  -8.68689435e-01  7.95394909e-01 -9.37937112e-01]
 [-1.08354131e+00  1.49135522e+00 -1.10530946e+00 -9.76610773e-01
  -1.49480865e-01  7.95394909e-01  1.98019012e-02]
 [-5.03098664e-01  7.61193547e-01  1.76208755e-01 -8.96923703e-01
  -5.52897011e-01  7.95394909e-01 -5.88491796e-01]
 [-5.03098664e-01  1.49135522e+00  1.45772697e+00  1.09749734e+00
   1.63032177e+00 -1.25723711e+00  1.63113308e+00]
 [-5.61142928e-01 -6.99129805e-01  8.16967863e-01 -7.22634873e-01
  -4.13653373e-01 -1.25723711e+00 -4.00826719e-01]
 [ 5.99742364e-01 -6.99129805e-01  1.13734742e+00 -4.03119554e-01
  -8.12297931e-01  7.95394909e-01 -8.53811388e-01]
 [-1.31571837e+00 -6.99129805e-01  1.13734742e+00 -4.32011443e-01
  -1.39876958e+00  7.95394909e-01 -1.41033541e+00]
 [-1.54833076e-01  3.10318712e-02 -1.44170799e-01  2.30115660e-01
  -7.52869961e-01 -1.25723711e+00 -7.76156873e-01]
 [ 1.06409648e+00  7.61193547e-01  1.13734742e+00 -5.44084701e-01
  -5.84563010e-01  7.95394909e-01 -5.75549377e-01]
 [ 6.57786629e-01  1.49135522e+00 -7.84929908e-01 -9.36951896e-01
   5.61312359e-02 -1.25723711e+00  1.68639721e-01]
 [ 3.67565306e-01  3.10318712e-02  1.77810653e+00 -5.41385852e-01
   1.58503505e-01 -1.25723711e+00  1.75110930e-01]
 [ 1.92997180e-02 -1.42929148e+00 -4.64550354e-01  5.28125413e-01
   1.21215707e+00  7.95394909e-01  1.03578180e+00]
 [ 1.81867192e+00  3.10318712e-02 -2.06644812e+00  1.77902774e+00
   2.45016749e+00 -1.25723711e+00  2.41414943e+00]
 [ 1.47040633e+00 -6.99129805e-01 -4.64550354e-01  3.85285276e-01
   1.15663313e+00  7.95394909e-01  1.18461962e+00]
 [ 1.18018501e+00  3.10318712e-02 -7.84929908e-01 -5.76698161e-01
   1.36814465e-01  7.95394909e-01  1.10398835e-01]
 [-3.87445466e-02  7.61193547e-01  1.76208755e-01  1.21678746e-01
   9.03738924e-01  7.95394909e-01  9.71069705e-01]
 [ 1.06409648e+00 -6.99129805e-01 -7.84929908e-01 -6.77407844e-01
  -1.15498476e+00  7.95394909e-01 -1.16442945e+00]
 [ 5.99742364e-01 -6.99129805e-01 -1.44170799e-01 -3.01386155e-02
   1.18855940e-02  7.95394909e-01 -2.54965656e-02]
 [-1.19962984e+00 -6.99129805e-01  4.96588309e-01 -2.70677088e-01
  -8.04923657e-01 -1.25723711e+00 -9.12052274e-01]
 [ 7.15830894e-01 -6.99129805e-01  8.16967863e-01  3.02927766e-01
   7.00122215e-02  7.95394909e-01  1.33306917e-02]
 [ 1.58649486e+00 -1.42929148e+00  4.96588309e-01  2.34689499e-01
  -2.05004807e-01 -1.25723711e+00 -2.45517690e-01]
 [-3.87010134e-01 -1.42929148e+00 -1.42568902e+00 -4.36612697e-02
   9.48418347e-01  7.95394909e-01  1.00989696e+00]
 [-3.28965870e-01  3.10318712e-02 -1.74606857e+00  3.64887658e-01
  -2.23223601e-01 -1.25723711e+00 -3.29643414e-01]
 [ 8.89963688e-01 -6.99129805e-01 -7.84929908e-01  4.88466536e-01
   7.46710274e-01  7.95394909e-01  6.47509227e-01]
 [ 1.70258339e+00 -6.99129805e-01  8.16967863e-01  3.73069432e-01
  -1.40805249e-01  7.95394909e-01 -1.87276804e-01]
 [ 1.92997180e-02  7.61193547e-01 -1.44170799e-01 -6.00305988e-01
  -4.64405727e-01  7.95394909e-01 -4.39653977e-01]
 [-9.09408516e-01  3.10318712e-02 -1.42568902e+00 -5.07096265e-01
  -5.58102381e-01  7.95394909e-01 -4.33182767e-01]
 [-1.14158557e+00  3.10318712e-02  1.76208755e-01 -3.05080311e-01
   5.87512719e-01 -1.25723711e+00  5.63383503e-01]
 [ 9.48007952e-01 -1.42929148e+00  1.13734742e+00 -2.23603479e-01
   7.12441590e-01 -1.25723711e+00  6.66922856e-01]
 [-3.87445466e-02  2.22151690e+00 -1.42568902e+00 -3.28460867e-01
   6.33493484e-01 -1.25723711e+00  6.15153180e-01]
 [ 5.41698100e-01  3.10318712e-02  1.76208755e-01 -9.30758748e-01
   2.86035061e-01  7.95394909e-01  2.39823026e-01]
 [-9.67888113e-02  1.49135522e+00  8.16967863e-01 -5.00817890e-01
  -9.32455213e-01  7.95394909e-01 -8.14984130e-01]
 [-6.77231458e-01 -1.42929148e+00  1.45772697e+00 -9.41781415e-01
  -3.74179320e-01  7.95394909e-01 -4.07297929e-01]
 [-9.67452781e-01 -1.42929148e+00  1.76208755e-01 -8.37435388e-01
   2.27301141e-02  7.95394909e-01  3.27443203e-02]
 [-8.51364252e-01  3.10318712e-02  1.76208755e-01  8.57583859e-01
  -3.73745540e-01  7.95394909e-01 -3.68470672e-01]
 [-1.48985116e+00 -6.99129805e-01 -1.42568902e+00 -9.76326683e-01
  -3.59430773e-01 -1.25723711e+00 -3.81413091e-01]
 [-1.78007249e+00  3.10318712e-02  8.16967863e-01 -3.79483318e-01
   7.11140248e-01  7.95394909e-01  7.38106161e-01]
 [ 1.35388247e-01 -6.99129805e-01  1.45772697e+00 -9.42832546e-01
  -6.73921855e-01  7.95394909e-01 -6.20847844e-01]
 [ 7.73439826e-02  3.10318712e-02  1.13734742e+00 -3.03461002e-01
  -6.35315363e-01  7.95394909e-01 -6.79088730e-01]
 [-1.78007249e+00 -6.99129805e-01  4.96588309e-01 -4.20619460e-01
  -4.53561207e-01 -1.25723711e+00 -3.61999462e-01]
 [ 8.31919423e-01 -1.42929148e+00  1.45772697e+00 -6.93970255e-01
  -8.95150064e-01 -1.25723711e+00 -9.76764369e-01]
 [ 4.83653835e-01  1.49135522e+00 -2.06644812e+00 -7.53344934e-01
   3.41992785e-01 -1.25723711e+00  3.88660845e-01]
 [ 5.99742364e-01  7.61193547e-01 -1.10530946e+00 -8.21441157e-01
   3.16833498e-01  7.95394909e-01  3.75718426e-01]
 [-1.48985116e+00 -1.42929148e+00 -4.64550354e-01 -4.44738647e-01
  -9.57180719e-01  7.95394909e-01 -1.05441888e+00]
 [-5.61142928e-01  2.95167857e+00 -1.42568902e+00  2.71172156e+00
   2.80413262e+00  7.95394909e-01  2.99008708e+00]
 [-5.61142928e-01  3.10318712e-02 -1.44170799e-01 -1.23121067e-01
   1.20330795e-01  7.95394909e-01  1.55697302e-01]
 [-1.60593969e+00  3.10318712e-02  1.76208755e-01  5.31591303e-01
   4.30484068e-01  7.95394909e-01  5.18085036e-01]
 [-1.78007249e+00  1.49135522e+00  8.16967863e-01 -8.84338544e-01
  -1.78977959e-01  7.95394909e-01 -1.87276804e-01]
 [ 6.57786629e-01  1.49135522e+00 -4.64550354e-01  3.59461551e-01
  -2.44912641e-01  7.95394909e-01 -2.19632852e-01]
 [ 1.23822928e+00 -6.99129805e-01 -2.06644812e+00 -4.12977455e-01
  -1.32936465e+00 -1.25723711e+00 -1.26149759e+00]
 [-3.28965870e-01 -6.99129805e-01  1.76208755e-01 -5.89737864e-01
  -1.21961810e+00  7.95394909e-01 -1.22914154e+00]
 [ 1.64453913e+00 -1.42929148e+00 -1.10530946e+00  2.29803161e-01
  -8.13599273e-01  7.95394909e-01 -9.12052274e-01]]


57     133
32     526
17     368
167      0
2      580
      ...
25     671
397    138
62       0
305      0
379      0
Name: Balance, Length: 96, dtype: int64

# E. Use Linear Regression to train a linear model on the training set. Check the coefficients of the linear regression model. Which feature is the most important? Which feature is the least important?

In [14]:
# "my_linreg" is instantiated as an "object" of LinearRegression "class" 

my_linreg = LinearRegression()

my_linreg.fit(X_train, y_train)

LinearRegression()

In [15]:
# print theta0 - using attribute "intercept_":
print(my_linreg.intercept_)

# print theta1 theta2 theta3 - using attribute "coef_":
print(my_linreg.coef_)

520.0391034603759
[ -17.23897686   24.91707959   11.65810466 -264.69553256  360.5601294
   -9.82859046  252.73642988]

In [16]:
# most important is rating
# least important is income

# F. Predict “balance” for the users in testing set. Then, compare the predicted balance with the actual balance by calculating and reporting the RMSE (as we saw in lab tutorial 4).

In [17]:
# make predictions on the testing set
y_prediction = my_linreg.predict(X_test)

print(y_prediction)

[ 316.89813114  677.5093907   489.03669272  -49.82989971  706.42913216
  864.96954115  897.65752581  108.20297732 -213.73474279  834.94198677
   11.05109139 -227.34447869  472.01450822    4.54554458 -228.17349827
  956.21537845  896.91570524  821.97824267   18.37144232  857.31517013
 1028.30326279  699.22168497 1176.9426756   666.28578465  643.94064891
  690.63628696  589.35273903  -29.37237394  575.15444917  406.78468032
  845.81453327  828.30862904   82.2376206   953.40592514 -184.74828227
  525.84335889 1045.19205022  535.04104472  107.26753118 -172.8968111
  497.84037664 1155.35533939  429.08674601  403.49872552  143.72087313
  764.78737012  431.24114308 1304.79656588  475.00132057   95.75404622
 -215.69000296    5.62900657  313.88797405  859.9328932   792.27147016
 1029.90210771 1500.40180297 1078.48617624  713.37981473 1072.97948262
  -64.12187718  488.60063387   92.3601712   440.414465    277.13284667
 1075.41508762  258.10181743  773.89657462  278.12447916  409.51029492
  335.56674013  989.87781589  978.31940615 1042.6230052   915.82319179
  150.95645254  516.7089988   733.47654088   74.84330655  556.47429962
 1096.60831626  359.12494251  204.54562103  407.76115868  113.50656023
  958.07237887  934.59051997    2.98452112 1627.80317193  636.31395153
  688.17824441  711.80910955  293.66354104 -219.28997401  -91.76701391
 -149.31642723]

In [18]:
from sklearn import metrics
import numpy as np

# calculate "Mean Square Error" (MSE):
mse = metrics.mean_squared_error(y_test, y_prediction)

# use numpy sqrt - take the square root & calculate "Root Mean Square Error" (RMSE)
rmse = np.sqrt(mse)

print(rmse)

143.24649739642265

In [19]:
# RMSE is 143.24649739642265 - this rmse is pretty high

# G. Now, use 10-fold Cross-Validation to evaluate the performance of a linear regression in predicting the balance. Thus, rather than splitting the dataset into testing and training, use Cross-Validation to evaluate the regression performance. What is the RMSE when you use cross validation?

In [28]:
# importing the method:
from sklearn.model_selection import cross_val_score

In [32]:
from sklearn.model_selection import cross_val_score

# apply 10-fold cross validation with "linear regression":

# "my_linreg" is instantiated as an "object" of LinearRegression "class". 
my_linreg = LinearRegression()

mse_list = cross_val_score(my_linreg, X, y, cv=10, scoring='neg_mean_squared_error')

print(mse_list)

[-23646.90415343 -32003.04401232 -35462.64435619 -37327.60719635
 -14341.32205939 -33628.37104224 -31631.99317834 -12491.00334951
 -20749.61212175 -23204.94743459]

In [33]:
# to calculate rmse, we have to make them positive
mse_list_positive = -mse_list

# using sqrt function to calculate rmse:
rmse_list = np.sqrt(mse_list_positive)
print(rmse_list)

[153.7754992  178.89394627 188.31527914 193.20353826 119.75525901
 183.38039983 177.85385343 111.76315739 144.04725656 152.331702  ]

In [34]:
# calculate avg RMSE as final result of cross validation:
print(rmse_list.mean())

160.33198910744142

In [35]:
# RMSE is 160.33198910744142 when we use cross validation.